services:

  audit-log-agent:
    build:
      context: ./audit-log-agent
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  audit-log-worker:
    build:
      context: ./audit-log-worker
      dockerfile: Dockerfile
    ports:
      - 8081:8080

  audit-log-query:
    build:
      context: ./audit-log-query
      dockerfile: Dockerfile
    ports:
      - 8082:8080

networks:
  audit-log-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1

volumes:
  audit-log-volume:
    driver: local